### ISSUE TITLE
generate figures for rms map

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/DR1_analysis#1]
We need to produce figures showing the rms maps
- [x] rms maps
- [x] rms histograms
- [x] for all regions in DR1

**Comment by jpinedaf** [comment]
@rfriesen @low-sky what do you think of the color schemes?

**Comment by rfriesen** [comment]
I like the histograms. Are they all bimodal? The rms maps don't necessarily
need to be in colour, but as long as we use colour-blind-friendly schemes
like you've done I think it's fine! I would recommend setting the zero
values to NaNs so that outside the mapped region the colour is white rather
than grey.

**Comment by jpinedaf** [comment]
now showing results for B18 and L1688 after re-baseline... I am setting the color for NaNs as non-white to avoid confusion about the existence of data, since white is present in the color scale while gray is not. However, I made now the gray color even lighter ('whiter'). 

I will do OrionA and NGC1333 Tomorrow

**Comment by jpinedaf** [comment]
I just added OrionA and NGC1333, in addition to a histogram of the rms for all lines for each region.

Notice that only L1688 shows the bimodal like behaviour, where some footprints in the norther part didn't reach the requested rms. These footprints would have been re-observed if the extension were approved

**Comment by jpinedaf** [comment]
change formatting of axes (via @rfriesen )

``` python
tick_labels.set_style(‘colons’)
tick_labels.set_xformat(‘hh:mm:ss')
tick_labels.set_yformat(‘dd:mm')
```

**Comment by jpinedaf** [comment]
to remove the edges of the current maps, we should use the following piece of code

``` python
from astropy.io import fits
from GAS.first_look import trim_edge_cube
import glob

file_list=glob.glob('*/*.fits')

for file_i in file_list:
    data, hd=fits.getdata( file_i, header=True)
    fits.writeto(file_i.replace('.fits','.fits_original'), data, header=hd, clobber=True)
    trim_edge_cube(data)
    fits.writeto(file_i, data, header=hd, clobber=True)
```

and the latest version of the GBT GAS pipeline (https://github.com/GBTAmmoniaSurvey/GAS/pull/143)

**Comment by jpinedaf** [comment]
@rfriesen look at this :)

**Comment by rfriesen** [comment]
Ha, thanks @jpinedaf 
The trouble is that trim_edge_cube won't work on the parameter maps (they are all zeroes rather than NaNs, it doesn't find an edge), so I've tried to do something further upstream in the data analysis. I have problems if I try to run anything using the NH3 fit information on the trimmed data, however.
